spring.application.name=GmailClone

# MySQL Configuration
spring.datasource.url=jdbc:postgresql://ep-lingering-king-azb89et6.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cdgTm3PMXxN7
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
